### ISSUE TITLE
/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- kaminari/grape (LoadError)

### ISSUE THREAD

**Issue by peterfei** [bsm/grape-kaminari#39]
could u help fix this issue?

**Comment by jaysonvirissimo** [comment]
[This](https://github.com/monterail/grape-kaminari/pull/38) and [that](https://github.com/monterail/grape-kaminari/pull/37) PR are meant to address this issue.

**Comment by tianbymy** [comment]
gem 'kaminari','0.17.0'
gem 'grape-kaminari', :require => 'kaminari/grape'

**Comment by dim** [comment]
Resolved via #51
