### ISSUE TITLE
Hand over development/Gem ownership

### ISSUE THREAD

**Issue by dim** [bsm/grape-kaminari#49]
This gem seems to be widely used but also unmaintained, would you mind to handing this over to us: https://github.com/bsm?

**Comment by subvertallchris** [comment]
I'd like to see this. Not sure if anyone else is having issues with newer versions of Grape but I'm guessing that some maintenance is in order.

**Comment by chytreg** [comment]
Hi, I can help with the hand over are you still interested? @dim  or @subvertallchris?

**Comment by dim** [comment]
@chytreg if you could transfer the ownership to `bsm`, we can take it from there.

**Comment by chytreg** [comment]
Sure, how about rubygems?

**Comment by dim** [comment]
Same pls, just transfer https://rubygems.org/gems/grape-kaminari to https://rubygems.org/profiles/bsm

**Comment by chytreg** [comment]
With the code, it's not a problem, but for rubygems ownership have to ask former employees of the company, hope they will reply shortly. 
cc @teamon & @Ostrzy

**Comment by teamon** [comment]
As per [docs](https://help.rubygems.org/discussions/questions/151-adding-another-owner) I'd need an email for the new owner.

**Comment by dim** [comment]
You can use `info@blacksquaremedia.com`, if that's OK.

**Comment by teamon** [comment]
```
Adding info@blacksquaremedia.com: Owner could not be found.
```

It must be an email of existing rubygems account.

**Comment by chytreg** [comment]
As for repo transfer,
```
You don’t have the permission to create public repositories on bsm
```
I've added @dim as a collaborator with Admin permission, but I don't think you would be able to transfer the repo since the only owner can do that ... but I can transfer to your GitHub account ... and then you can move to your organization. WDYT?

**Comment by dim** [comment]
Sure, you can transfer it to my "private" GH handle, which is https://github.com/dim

**Comment by dim** [comment]
Actually, I could do it myself, the GH transfer is complete.

**Comment by dim** [comment]
Hi again, 

Sorry, my bad, didn't check it properly, getting:

```
You do not have permission to push to this gem. Ask an owner to add you with: gem owner grape-kaminari --add dimitrij@blacksquaremedia.com
```

**Comment by chytreg** [comment]
Done
