### ISSUE TITLE
Breaks in Grape >= 1.2.0, undefined method 'paginate'

### ISSUE THREAD

**Issue by subvertallchris** [bsm/grape-kaminari#50]
All of my calls to `paginate` broke after an update. While the release notes don't mention it, the [upgrade guide](https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#upgrading-to--120) for Grape 1.2.0 describes a change to the `Grape::API` class that is probably the cause of this.

> In an effort to make APIs re-mountable, The class Grape::API no longer refers to an API instance, rather, what used to be Grape::API is now Grape::API::Instance and Grape::API was replaced with a class that can contain several instances of Grape::API.
> 
> This changes were done in such a way that no code-changes should be required. However, if experiencing problems, or relying on private methods and internal behaviour too deeply, it is possible to restore the prior behaviour by replacing the references from Grape::API to Grape::API::Instance.

I found that I can fix it by changing all calls of `paginate` to `base.paginate`:

```
# old
paginate per_page: 50, max_per_page: 50

# new
base.paginate per_page: 50, max_per_page: 50
```

I'm not sure where in this gem the fix needs to be applied or if this is even correct but I didn't see any issues about this so thought I'd toss it out there just in case someone else hits a wall.

**Comment by merhard** [comment]
Rather than adding `include Grape::Kaminari` in the API, try using `Grape::API::Instance.include(Grape::Kaminari)` in an initializer or boot file.

For example, in a Rails app add:
```ruby
# config/initializers/grape-kaminari.rb

Grape::API::Instance.include(Grape::Kaminari)
```

(I based this solution on how `grape-swagger` extends its DSL addition: https://github.com/ruby-grape/grape-swagger/blob/71612befaaa1fff1bfc1db5c787eb916ab8efa9e/lib/grape-swagger.rb#L171)
