### ISSUE TITLE
undefined method `paginate' with rails 6

### ISSUE THREAD

**Issue by zaoldreck** [bsm/grape-kaminari#53]
ruby 2.6.6
rails 6.0.2.2

error undefined method `paginate'

Noted:
 - include Grape::Kaminari in api
 - try with rails loader classic but still error

**Comment by dim** [comment]
I unfortunately cannot recreate your issue. Did you include a `paginate` block/line in the endpoint description? I would need to see some code or a small demo app.

**Comment by zaoldreck** [comment]
```
class CustomersAPI < Grape::API
  include Grape::Kaminari

  resource :customers do
    desc 'GET /api/v1/customers'
    paginate per_page: 20, max_per_page: 30, offset: 1
    params do
      optional :query, type: String
    end
    get do
      users = User.search_by_email(params[:query])
      render_json(:ok, CustomerSerializer.new(users))
    end
  end
end
```

**Comment by dim** [comment]
Closing in favour of #54

**Comment by bsodmike** [comment]
This is breaking in Ruby `ruby 2.5.1p57` with latest version `Using grape-kaminari 0.3.0`

**Comment by bsodmike** [comment]
Adding `config/initializers/grape-kaminari.rb` got it working:

```
Grape::API::Instance.include(Grape::Kaminari)
```

**Comment by dim** [comment]
@bsodmike CI looks OK - https://travis-ci.org/github/bsm/grape-kaminari. Could you maybe submit a PR with a test to demo the issue?

**Comment by zaoldreck** [comment]
Please upgrade grape version and grape-kaminari
```
gem 'grape', '~> 1.5'
gem 'grape-kaminari', '~> 0.4.0'
```
@smridge

**Comment by smridge** [comment]
@zaoldreck works like a charm! Many thanks!
